### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by jpfxgood** [jpfxgood/ped#2]
- [x] - Package this thing and push a release to pypi
    Note: I already did a dry run on the testpypi site and it looks pretty simple just need to look at the details a bit
- [x] - Put in a test to validate that the blank bottom and right of the screen get cleared properly
- [x] - Finish the user documentation

**Comment by jpfxgood** [comment]
Packaging went into 1.1.0 and 1.1.2 has changes to validate_screen that makes sure we also validate the blank space, this found a bug in the tests where we were actually not validating any of the wrapped cases properly, gotta test the tests ;-)

**Comment by jpfxgood** [comment]
Finished up these todos...
